version: 2.1

anchors:
  workspace_root: &workspace_root ~/repo

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

orbs:
  aws-s3: circleci/aws-s3@3.0.0 # use the AWS S3 orb in your config

jobs:
  build:
    executor: build_env
    steps:
      - setup
      - lint
      - run_tests
  deploy:
    executor: build_env
    steps:
      - *attach_workspace
      - build_output
      - deploy:
          bucket: "jpgt-or-stg-collection-online-20"
          path: "test"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          # filters:
          #   branches:
          #     only: main
          requires:
            - build

commands:
  setup:
    steps:
      - checkout
      - run: npm install
  lint:
    steps:
      - run: npm run lint
  run_tests:
    steps:
      - run:
          name: Run unit tests
          command: npm run test:unit
      - persist_to_workspace:
          root: *workspace_root # absolute path or relative to working_directory
          paths: . # paths relative to the workspace root
  build_output:
    steps:
      - run: npm run build:jsdoc
      - persist_to_workspace:
          root: *workspace_root # absolute path or relative to working_directory
          paths: . # paths relative to the workspace root

  deploy:
    description: "Deploy to s3"
    parameters:
      bucket:
        type: string
        default: S3_BUCKET
      path:
        type: string
        default: "prod"
      additional_arguments:
        type: string
        default: ' --acl public-read --cache-control "max-age=86400" '

    steps:
      - aws-s3/sync:
          from: jsdoc
          to: "s3://<< parameters.bucket >>/<< parameters.path >>"
          arguments: " --delete << parameters.additional_arguments >>"
          # overwrite: true # default is false

executors:
  build_env:
    docker:
      - image: cimg/node:15.4.0
    working_directory: ~/repo
    environment: CI:true
